proyecto_prueba/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('users','UsersController');


Route::get('users/{user}/pay', [
		'uses'	=> 'UsersController@pay',
		'as'	=> 'users.pay'
	]);

Route::get('users/{user}/payments', [
		'uses'	=> 'UsersController@payments',
		'as'	=> 'users.payments'
	]);

Route::resource('payments','PaymentsController');


Route::post('payments/{id}/store', [
		'uses'	=> 'PaymentsController@store',
		'as'	=> 'payments.store'
	]);

proyecto_prueba/app/Payment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    
	 /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'amount', 'date', 'user_id', 
    ];


    public function user(){

    	return $this->belongsTo('App\User');
    }
}

proyecto_prueba/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'type', 'identification', 'salary',
    ];

    public function payments(){

        return $this->hasMany('App\Payment');
    }

    public function scopeSearchUser($query, $name){

        return $query->where('name','=', $name);
    }

    
}

proyecto_prueba/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

proyecto_prueba/app/Http/Controllers/PaymentsController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Payment;
use App\Http\Requests\PaymentRequest;
use Laracasts\Flash\Flash;

class PaymentsController extends Controller
{
    
        public function index(){

        //Consulta para mostrar el historial de pagos
        $history = DB::table('users as u')
            ->leftJoin('payments as p', 'u.id', '=', 'p.user_id')
            ->select('u.id', 'u.name', 'u.salary', 'u.identification', DB::raw('COUNT(p.id) as numero_pagos, IF(ISNULL(SUM(p.amount)), 0, SUM(p.amount)) as valor'))
            ->groupBy('u.id', 'u.name', 'u.salary', 'u.identification')
            ->paginate(5);

        return view('payments.index')->with('history', $history);
        
    }

   
    public function store(PaymentRequest $request, $id){

        $payment = new Payment($request->all());
        $payment->user_id = $id;
        $payment->save();
        Flash::success('El pago ha sido creado exitosamente');
        return redirect()->route('users.payments', $id);
    }

    public function edit(Payment $payment){

        return view('payments.edit')->with('payment', $payment);
    }

    public function update(PaymentRequest $request, Payment $payment){

        $payment->fill($request->all());
        $user = $payment->user_id;
        $payment->save();
        Flash::success('El pago ha sido actualizado exitosamente');
        return redirect()->route('users.payments', $user);
    }

    public function destroy(Payment $payment){
        
        $user = $payment->user_id;
        $payment->delete();
        Flash::error('El pago ha sido borrado exitosamente');
        return redirect()->route('users.payments', $user);
    }

}

proyecto_prueba/app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Validator;
use Illuminate\Http\Request;
use App\User;
use App\Http\Requests\UserRequest;
use App\Http\Requests\UserUpdateRequest;
use Laracasts\Flash\Flash;
use Illuminate\Validation\Rule;

class UsersController extends Controller
{
    
    public function create(){

    	return view('users.create');
    }


    public function store(UserRequest $request){

    	$user = new User($request->all());
    	$user->save();
    	Flash::success('El usuario '.$user->name.' fue creado exitosamente');
    	return redirect()->route('users.index');
    }

    public function index(){

    	$users = User::orderBy('id', 'DESC')->paginate(5);
    	return view('users.index')->with('users', $users);
    }

    public function edit(User $user){
    	
    	return view('users.edit')->with('user', $user);
    }

    public function update(UserUpdateRequest $request, User $user){

    	
        $validator = Validator::make($request->all(), [
            'identification' => 
            ['required', Rule::unique('users')->ignore($user->identification)]
        ]);
        $user->fill($request->all());
        $user->save();
        Flash::success('El usuario '.$user->name.' ha sido actualizado exitosamente');
        return redirect()->route('users.index');
    }

    public function destroy(User $user){
        
        $user->delete();
        Flash::error('El usuario '. $user->name.' ha sido borrado exitosamente');
        return redirect()->route('users.index');
    }

    public function pay(User $user){
        
        return view('users.pay')->with('user', $user);
    }

    public function payments(User $user){
        
        $user->payments;
        return view('users.payments')->with('user', $user);
    }



}

proyecto_prueba/resources/views/payments/create.blade.php
@extends('template.main')

@section('title', 'Crear pago')

@section('content')

				{{dd($users)}}
  				{!! Form::open(['route' => 'payments.store', 'method' => 'POST']) !!}

  				<div class="form-group">
					{!! Form::label('user_id', 'Usuario') !!}
					{!! Form::select('user_id', $users->name, null, [ 'class' => 'form-control form-control', 'placeholder' => 'Seleccione el tipo de documento', 'required']) !!}
				</div>

  				<div class="form-group">
	  				{!! Form::label('date', 'Fecha') !!}
					{!! Form::date('date', null, ['class' => 'form-control', 'required']) !!}
				</div>
				
				<div class="form-group">
	  				{!! Form::label('amount', 'Valor') !!}
					{!! Form::number('amount', null, ['class' => 'form-control', 'placeholder' => 'ingrese el valor a pagar', 'required']) !!}
				</div>
				
				<div class="form-group">
					<br>
					{!! Form::submit('Crear Usuario', ['class' => 'btn btn-danger' ]) !!}
				</div>
				
				{!! Form::close() !!}
			
	



@endsection

proyecto_prueba/resources/views/payments/edit.blade.php
@extends('template.main')

@section('title', 'Editar pago')

@section('content')
				
				
  				{!! Form::open(['route' => ['payments.update', $payment->id], 'method' => 'PUT']) !!}


  				<div class="form-group">
	  				{!! Form::label('date', 'Fecha') !!}
					{!! Form::date('date', $payment->date, ['class' => 'form-control', 'required']) !!}
				</div>
				
				<div class="form-group">
	  				{!! Form::label('amount', 'Valor') !!}
					{!! Form::number('amount', $payment->amount, ['class' => 'form-control', 'placeholder' => 'ingrese el valor a pagar', 'required']) !!}
				</div>
				
				<div class="form-group">
					<br>
					{!! Form::submit('Editar Pago', ['class' => 'btn btn-danger' ]) !!}
				</div>
				
				{!! Form::close() !!}
			
	



@endsection

proyecto_prueba/resources/views/payments/index.blade.php
@extends('template.main')

@section('title', 'Historial de pagos')
@section('content')

	
	<table class="table table-striped">
		<thead>
			<th></th>
			<th>Identificacion</th>	
			<th>Nombre</th>	
			<th>Salario</th>
			<th>Cantidad de pagos</th>	
			<th>Valor total</th>
			<th>Ver pagos</th>	
		</thead>
		<tbody>
			@foreach($history as $payment)
			<tr>
				<td><a href="{{route('users.pay', $payment->id)}}" class="btn btn-default"><span class="fa fa-plus-circle" aria-hidden="true"></span></a></td>
				<td>{{ $payment->identification }}</td>	
				<td>{{ $payment->name }}</td>	
				<td>{{ $payment->salary }}</td>
				<td>{{ $payment->numero_pagos }}</td>	
				<td>{{ $payment->valor }}</td>
				<td><a href="{{route('users.payments', $payment->id)}}" class="btn btn-default"><span class="fa fa-eye" aria-hidden="true"></span></a></td>	
			</tr>
			@endforeach
		</tbody>
	</table>
	<div class="text-center">
	{!! $history->render()!!}
	</div>
@endsection

proyecto_prueba/resources/views/template/main.blade.php
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('title', 'Default') | Medrar</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('plugins/landing/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{asset('plugins/bootstrap/css/bootstrap.css')}}"> 

    <!-- Custom fonts for this template -->
    <link href="{{ asset('plugins/landing/vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:200,300,600,200italic,300italic,600italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="{{ asset('plugins/landing/css/landing-page.css')}}" rel="stylesheet">

  </head>

  <body>

  @include('template.partials.nav')

    <div class="container">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><b>@yield('title')</b></h3>
        </div>
        <div class="panel-body">
          @include('flash::message')
          @include('template.partials.errors')          
          @yield('content')
        </div>
      </div>
    </div>
    
   <!-- Footer -->
    <footer>
      <div class="container">
        <p class="copyright text-muted small">Copyright &copy; Medrar 2017. Todos los derechos reservados</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src=" {{ asset('plugins/jquery/js/jquery-3.2.1.js')}} "></script>
    <script src=" {{ asset('plugins/bootstrap/js/bootstrap.js')}} "></script>

    <script>
      
      function deleteItem(id){
            if(confirm('¿Esta seguro que desea borrarlo?')) {
                var form = $('#form-delete');
                var url = form.attr('action').replace(':ITEM_ID', id);
                form.attr('action', url);

                form.submit();
            }
        }

    </script>
    
    

  </body>

</html>

proyecto_prueba/resources/views/template/partials/errors.blade.php
@if(count($errors) > 0)		
    <div class="alert alert-danger" role="alert">
    	<ul>
    	@foreach($errors->all() as $error)	
    		<li>{{ $error }}</li>
    	@endforeach	
    	</ul>
    </div>
@endif

proyecto_prueba/resources/views/template/partials/nav.blade.php
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">      
        <li>
            <a class="navbar-brand" style="padding-top: 5px;" href="/">
              <img src="{{asset('logo.png')}}" width="40" height="40" class="d-inline-block align-top" alt="">
            </a>
        </li>
        <li><a class="navbar-brand" href="">Medrar</a></li>  
      </ul> 

      
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
              <a class="nav-link" href="/">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{route('users.index')}}">Usuarios</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{route('payments.index')}}">Pagos</a>
            </li>
          </ul>
        </div>
       
    </nav>
        

proyecto_prueba/resources/views/users/create.blade.php
@extends('template.main')

@section('title', 'Crear usuario')

@section('content')


	
	
  				{!! Form::open(['route' => 'users.store', 'method' => 'POST']) !!}

  				<div class="form-group">
	  				{!! Form::label('name', 'Nombre') !!}
					{!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Nombre completo', 'required']) !!}
				</div>

				<div class="form-group">
					{!! Form::label('type', 'Tipo de documento') !!}
					{!! Form::select('type', ['CC' => 'Cedula de ciudadania', 'TI' => 'Tarjeta de identidad', 'CE' => 'Cedula de extranjeria'], null, [ 'class' => 'form-control form-control', 'placeholder' => 'Seleccione el tipo de documento', 'required']) !!}
				</div>

				<div class="form-group">
	  				{!! Form::label('identification', 'Numero de identificacion') !!}
					{!! Form::number('identification', null, ['class' => 'form-control', 'placeholder' => 'Numero de identificacion', 'required']) !!}
				</div>
				
				<div class="form-group">
	  				{!! Form::label('salary', 'Salario') !!}
					{!! Form::number('salary', null, ['class' => 'form-control', 'placeholder' => 'ingrese el salario', 'required']) !!}
				</div>
				
				<div class="form-group">
					<br>
					{!! Form::submit('Crear Usuario', ['class' => 'btn btn-danger' ]) !!}
				</div>
				
				{!! Form::close() !!}
			
	



@endsection

proyecto_prueba/resources/views/users/edit.blade.php
@extends('template.main')

@section('title', 'Editar usuario '.$user->name)

@section('content')


	
	
  				{!! Form::open(['route' => ['users.update', $user], 'method' => 'PUT']) !!}

  				<div class="form-group">
	  				{!! Form::label('name', 'Nombre') !!}
					{!! Form::text('name', $user->name, ['class' => 'form-control', 'placeholder' => 'Nombre completo', 'required']) !!}
				</div>

				<div class="form-group">
					{!! Form::label('type', 'Tipo de documento') !!}
					{!! Form::select('type', ['CC' => 'Cedula de ciudadania', 'TI' => 'Tarjeta de identidad', 'CE' => 'Cedula de extranjeria'], $user->type, [ 'class' => 'form-control form-control', 'placeholder' => 'Seleccione el tipo de documento', 'required']) !!}
				</div>

				<div class="form-group">
	  				{!! Form::label('identification', 'Numero de identificacion') !!}
					{!! Form::number('identification', $user->identification, ['class' => 'form-control', 'placeholder' => 'Numero de identificacion', 'required']) !!}
				</div>
				
				<div class="form-group">
	  				{!! Form::label('salary', 'Salario') !!}
					{!! Form::number('salary', $user->salary, ['class' => 'form-control', 'placeholder' => 'ingrese el salario', 'required']) !!}
				</div>
				
				<div class="form-group">
					<br>
					{!! Form::submit('Editar Usuario', ['class' => 'btn btn-danger' ]) !!}
				</div>
				
				{!! Form::close() !!}
			
	



@endsection

proyecto_prueba/resources/views/users/index.blade.php
@extends('template.main')

@section('title', 'Listado de usuarios')
@section('content')

	<a href="{{route('users.create')}}" class="btn btn-default"><span class="fa fa-plus-circle" aria-hidden="true"></span></a>&nbsp;Crear usuario nuevo <hr>
	<form action="{{route('users.destroy', ':ITEM_ID')}}" method="POST" id="form-delete">	
		<input name="_method" type="hidden" value="DELETE">
		{!! csrf_field() !!}
		<table class="table table-striped">
			<thead>
				<th>ID</th>	
				<th>Nombre</th>	
				<th>Tipo documento</th>
				<th>Salario</th>	
				<th>Accion</th>	
			</thead>
			<tbody>
				@foreach($users as $user)
				<tr>
					<td>{{ $user->identification }}</td>	
					<td>{{ $user->name }}</td>	
					<td>
					@if($user->type == "CC")
						Cedula de ciudadania
					@elseif($user->type == "TI")
						Tarjeta de identidad
					@else
						Cedula de extranjeria		
					</td>
					@endif
					<td>{{ $user->salary }}</td>	
					<td><a href="{{route('users.edit', $user->id)}}" class="btn btn-default"><span class="fa fa-pencil" aria-hidden="true"></span></a> <a href="{{route('users.pay', $user->id)}}" class="btn btn-success"><span class="fa fa-usd" aria-hidden="true"></span></a> <a href="{{route('users.payments', $user->id)}}" class="btn btn-warning"><span class="fa fa-folder-open-o" aria-hidden="true"></span></a> 
					
					<a href="javascript:deleteItem({{ $user->id }})" class="btn btn-danger"><span class="fa fa-times" aria-hidden="true"></span></a> 
					</td>	
				</tr>
				@endforeach
			</tbody>
		</table>
	</form>
	<div class="text-center">
	{!! $users->render()!!}
	</div>
@endsection

proyecto_prueba/resources/views/users/pay.blade.php
@extends('template.main')

@section('title', 'Crear pago para '.$user->name)

@section('content')
				
				
  				{!! Form::open(['route' => ['payments.store', $user->id], 'method' => 'POST']) !!}

  				<div class="form-group">
					{!! Form::hidden('user_id', $user->id) !!}
				</div>

  				<div class="form-group">
	  				{!! Form::label('date', 'Fecha') !!}
					{!! Form::date('date', null, ['class' => 'form-control', 'required']) !!}
				</div>
				
				<div class="form-group">
	  				{!! Form::label('amount', 'Valor') !!}
					{!! Form::number('amount', null, ['class' => 'form-control', 'placeholder' => 'ingrese el valor a pagar', 'required']) !!}
				</div>
				
				<div class="form-group">
					<br>
					{!! Form::submit('Crear Pago', ['class' => 'btn btn-danger' ]) !!}
				</div>
				
				{!! Form::close() !!}
			
	



@endsection

proyecto_prueba/resources/views/users/payments.blade.php
@extends('template.main')

@section('title', 'Pagos de '.$user->name)
@section('content')

	<a href="{{route('users.pay', $user->id)}}" class="btn btn-default"><span class="fa fa-plus-circle" aria-hidden="true"></span></a>&nbsp;Crear pago <hr>
	<form action="{{route('payments.destroy', ':ITEM_ID')}}" method="POST" id="form-delete">	
		<input name="_method" type="hidden" value="DELETE">
		{!! csrf_field() !!}
		<table class="table table-striped">
			<thead>
				<th>ID</th>	
				<th>Fecha</th>	
				<th>Valor</th>	
				<th>Accion</th>	
			</thead>
			<tbody>
				@foreach($user->payments as $payment)
				<tr>
					<td>{{ $payment->id }}</td>	
					<td>{{ $payment->date}}</td>	
					<td>{{ $payment->amount }}</td>				
					<td>
						<a href="{{route('payments.edit', $payment->id)}}" class="btn btn-default"><span class="fa fa-pencil" aria-hidden="true"></span></a> 
						<a href="javascript:deleteItem({{ $payment->id }})" class="btn btn-danger"><span class="fa fa-times" aria-hidden="true"></span></a>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</form>
@endsection